name: "Publish App to GutHub Pages ğŸ“Ÿ"

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: "Checkout ğŸ‰"
        uses: actions/checkout@v2

      - name: "Setup Node ğŸƒâ€â™€ï¸ğŸ¥ˆ"
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      
      - name: "Install dependencies ğŸ“¦"
        run: npm run build

      - name: Deploy â˜ğŸŒª
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: "${{TOKEN}}"
          publish_dir: dist/angular-template-demo
          enable_jekyll: true